apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ze8jcs3nn-go-gitops
  description: This is GitOps manifest for ze8jcs3nn-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ze8jcs3nn-go
    backstage.io/kubernetes-id: ze8jcs3nn-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ze8jcs3nn-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ze8jcs3nn-go
